""" generated by open AI
 However, I have a tested version on iMac at
  "./Library/Mobile Documents/com~apple~CloudDocs/EX-Dropbox/git_clones/bmlam-git_clones/apex_konten_bewegungen/supporting_objects/expand_master_script.py"
"""
import re

def read_script(script_path):
    with open(script_path, 'r') as file:
        return file.read()

def concatenate_scripts(master_script_content):
    concatenated_script = ''
    
    lines = master_script_content.split('\n')
    for line in lines:
        if line.startswith('--') or line.startswith('@@'):
            # Extract the script path from the line
            script_path = re.search(r'@@\s*(\S+)', line)
            if script_path:
                child_script_content = read_script(script_path.group(1))
                concatenated_script += child_script_content + '\n'
        else:
            concatenated_script += line + '\n'
    
    return concatenated_script

def main():
    master_script_path = 'path_to_your_master_script.sql'
    master_script_content = read_script(master_script_path)
    
    concatenated_script = concatenate_scripts(master_script_content)
    
    with open('concatenated_script.sql', 'w') as file:
        file.write(concatenated_script)

if __name__ == '__main__':
    main()
