REM  EXPERIMENTAL STAGE. THIS FUNCTION SHOULD BE PACKAGED IN MORE ADVANCED STAGE 
CREATE OR REPLACE FUNCTION  fn_app_base_objects_report (
	pi_app_name VARCHAR2 
) RETURN CLOB 
AS
	l_return CLOB;
BEGIN 

-- SELECT * FROM APEX_APPLICATIONS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_AUTH
;
-- SELECT * FROM APEX_APPLICATION_LISTS WHERE APPLICATION_NAME = pi_app_name
;

	FOR lr IN (
		SELECT list_of_values_name
			,  list_of_values_query
			, lov_type = 'Dynamic'
		FROM APEX_APPLICATION_LOVS 
		WHERE APPLICATION_NAME = pi_app_name
		  AND 
		)
	;
-- SELECT * FROM APEX_APPLICATION_LOV_COLS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_PAGE_IR
;
-- SELECT * FROM APEX_APPLICATION_PAGE_IR
;
-- SELECT * FROM APEX_APPLICATION_PAGE_IR_COND
;
-- SELECT * FROM APEX_APPLICATION_PAGE_ITEMS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_PAGE_ITEMS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_PAGE_REGIONS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_PAGE_REGIONS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_PAGE_TREES WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_RPT_QRY_STMTS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_RPT_QRY_STMTS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_RPT_QUERIES WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_RPT_QUERIES WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_SUPP_OBJECTS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPLICATION_SUPP_OBJ_SCR
;
-- SELECT * FROM APEX_APPLICATION_TREES WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_AUTOMATIONS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_AUTOMATIONS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_AUTOMATIONS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PAGE_IG_COLUMNS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PAGE_IG_COLUMNS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PAGE_IG_RPT_COMPUTES WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PAGE_MAP_LAYERS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PAGE_MAP_LAYERS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PLUGINS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_PLUGINS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_SEARCH_CONFIGS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_SEARCH_CONFIGS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_TASKDEFS WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_USER_INTERFACES WHERE APPLICATION_NAME = pi_app_name
;
-- SELECT * FROM APEX_APPL_WEB_SRC_PARAMETERS WHERE APPLICATION_NAME = pi_app_name
;

END fn_app_base_objects_report;
/
